version: "3.9"
services:
  my-mysql:
    image: mysql:5.7
    volumes:
      - ./mydal-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb